#!/usr/bin/env bash
/usr/bin/ovs-vsctl --no-wait -- set-manager tcp:192.168.11.10:6641 tcp:192.168.11.12:6641 tcp:192.168.11.14:6641 
/usr/bin/ovs-vsctl --no-wait -- set Open_vSwitch . other_config:local_ip=192.168.13.12
/usr/bin/ovs-vsctl --no-wait -- set Open_vSwitch . other_config:provider_mappings=physnet1:br-ex
/usr/bin/ovs-vsctl --no-wait -- set Open_vSwitch . external_ids:system-id=`cat /proc/sys/kernel/random/uuid`
/usr/bin/ovs-vsctl --no-wait -- set Open_vSwitch . external_ids:odl_os_hostconfig_config_odl_l2='{"supported_vnic_types": [{"vnic_type": "normal", "vif_type": "ovs", "vif_details": {} }], "allowed_network_types": ["flat", "vlan", "vxlan"], "datapath_types": ["netdev", "system"], "bridge_mappings": {"physnet1":"br-ex"} }'
/usr/bin/ovs-vsctl --no-wait -- set Open_vSwitch . external_ids:odl_os_hostconfig_hostid="host-192-168-11-12"
/usr/sbin/ovs-vswitchd unix:/run/openvswitch/db.sock -vconsole:emer -vsyslog:err -vfile:info --mlockall --log-file=/var/log/kolla/openvswitch/ovs-vswitchd.log
